"""
Export products to MySQL SQL file with CREATE TABLE and INSERT statements.
"""

import logging
from pathlib import Path
from typing import Dict, List

from config import DATA_DIR
from utils import setup_logger

logger = setup_logger("export_mysql")


def escape_sql(val) -> str:
    """Escape a Python value for SQL."""
    if val is None:
        return "NULL"
    if isinstance(val, bool):
        return "1" if val else "0"
    if isinstance(val, (int, float)):
        return str(val)
    if isinstance(val, dict) or isinstance(val, list):
        # Store as JSON string
        import json
        escaped = json.dumps(val, ensure_ascii=False).replace("'", "\\'")
        return f"'{escaped}'"
    # String
    escaped = str(val).replace("'", "\\'")
    return f"'{escaped}'"


CREATE_TABLE_SQL = """
-- ============================================================
-- Bách Hóa Tươi — Products Table
-- Generated by ETL Pipeline
-- ============================================================

DROP TABLE IF EXISTS `products`;

CREATE TABLE `products` (
  `id` VARCHAR(20) NOT NULL,
  `sku` VARCHAR(50) NOT NULL,
  `slug` VARCHAR(255) NOT NULL,
  `barcode` VARCHAR(50) DEFAULT NULL,
  `name` VARCHAR(500) NOT NULL,
  `brand` VARCHAR(255) DEFAULT NULL,
  `category` VARCHAR(100) DEFAULT NULL,
  `description` TEXT DEFAULT NULL,
  `price` INT NOT NULL DEFAULT 0,
  `salePrice` INT DEFAULT NULL,
  `unit` VARCHAR(20) DEFAULT 'cái',
  `stock` INT NOT NULL DEFAULT 0,
  `sold` INT NOT NULL DEFAULT 0,
  `rating` DECIMAL(2,1) NOT NULL DEFAULT 0,
  `reviewCount` INT NOT NULL DEFAULT 0,
  `imageUrl` VARCHAR(500) DEFAULT NULL,
  `gallery` JSON DEFAULT NULL,
  `nutrition` JSON DEFAULT NULL,
  `tags` JSON DEFAULT NULL,
  `badges` JSON DEFAULT NULL,
  `featured` TINYINT(1) NOT NULL DEFAULT 0,
  `active` TINYINT(1) NOT NULL DEFAULT 1,
  `createdAt` DATETIME DEFAULT NULL,
  `updatedAt` DATETIME DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sku` (`sku`),
  UNIQUE KEY `uk_slug` (`slug`),
  KEY `idx_category` (`category`),
  KEY `idx_brand` (`brand`),
  KEY `idx_featured` (`featured`),
  KEY `idx_active` (`active`),
  FULLTEXT KEY `ft_search` (`name`, `description`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================
-- Data
-- ============================================================
""".strip()


def build_insert_sql(products: List[Dict]) -> str:
    """Build a multi-row INSERT statement."""
    if not products:
        return ""

    columns = [
        "id", "sku", "slug", "barcode", "name", "brand", "category",
        "description", "price", "salePrice", "unit", "stock", "sold",
        "rating", "reviewCount", "imageUrl", "gallery", "nutrition",
        "tags", "badges", "featured", "active", "createdAt", "updatedAt",
    ]

    value_rows = []
    for p in products:
        row = [
            escape_sql(p.get("id")),
            escape_sql(p.get("sku")),
            escape_sql(p.get("slug")),
            escape_sql(p.get("barcode")),
            escape_sql(p.get("name")),
            escape_sql(p.get("brand")),
            escape_sql(p.get("category")),
            escape_sql(p.get("description")),
            escape_sql(p.get("price", 0)),
            escape_sql(p.get("salePrice")),
            escape_sql(p.get("unit", "cái")),
            escape_sql(p.get("stock", 0)),
            escape_sql(p.get("sold", 0)),
            escape_sql(p.get("rating", 0)),
            escape_sql(p.get("reviewCount", 0)),
            escape_sql(p.get("imageUrl", "")),
            escape_sql(p.get("gallery", [])),
            escape_sql(p.get("nutrition", {})),
            escape_sql(p.get("tags", [])),
            escape_sql(p.get("badges", [])),
            escape_sql(p.get("featured", False)),
            escape_sql(p.get("active", True)),
            escape_sql(p.get("createdAt")),
            escape_sql(p.get("updatedAt")),
        ]
        value_rows.append("(" + ", ".join(row) + ")")

    # Insert in batches of 500 to avoid huge SQL statements
    col_list = ", ".join(f"`{c}`" for c in columns)
    parts = []
    batch_size = 500
    for i in range(0, len(value_rows), batch_size):
        batch = value_rows[i:i + batch_size]
        sql = f"INSERT INTO `products` ({col_list}) VALUES\n"
        sql += ",\n".join(batch) + ";"
        parts.append(sql)

    return "\n\n".join(parts)


def export_mysql(products: List[Dict], path: Path) -> Path:
    """Export products to SQL file."""
    logger.info("Exporting %d products to SQL: %s", len(products), path)

    with open(path, "w", encoding="utf-8") as f:
        f.write(CREATE_TABLE_SQL)
        f.write("\n\n")
        f.write(build_insert_sql(products))

    logger.info("SQL export complete: %s (%.1f MB)", path, path.stat().st_size / 1e6)
    return path


def run(products: List[Dict]) -> Path:
    """Run SQL export step."""
    path = export_mysql(products, DATA_DIR / "products.sql")
    return path


if __name__ == "__main__":
    logger.info("Run via main.py")